[tool.poetry]
name = "asyncio-redis-rate-limit"
description = "Rate limiter for async functions using Redis as a backend"
version = "0.2.0"
license = "MIT"
readme = "README.md"

authors = [
  "Nikita Sobolev <mail@sobolevn.me>"
]

repository = "https://github.com/wemake-services/asyncio-redis-rate-limit"

keywords = [
  "asyncio",
  "rate-limiter",
  "redis",
  "redis-py",
  "aioredis",
]

classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.dependencies]
python = "^3.7"

redis = { version = ">=4.3", optional = true }
aioredis = { version = ">=2.0", optional = true }
typing-extensions = ">=3.10"

[tool.poetry.dev-dependencies]
mypy = "^0.971"
types-redis = "^4.3"
types-mock = "^4.0"

wemake-python-styleguide = "^0.16"
flake8-pytest-style = "^1.6"
doc8 = "^0.11"
nitpick = "^0.32"

safety = "^2.1"

pytest = "^7.1"
pytest-cov = "^3.0"
pytest-randomly = "^3.12"
pytest-asyncio = "^0.19"
pytest-freezegun = "^0.4"
pytest-repeat = "^0.9"

[tool.poetry.extras]
redis = ["redis"]
aioredis = ["aioredis"]
dev = ["redis", "aioredis"]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.nitpick]
style = "https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/master/styles/nitpick-style-wemake.toml"
