name: test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: test-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        redis-image: ['redis:7.0-alpine']
        env-type: ['redis']

        include:
          - python-version: '3.10'
            env-type: 'aioredis'
            redis-image: 'redis:7.0-alpine'
          - python-version: '3.9'
            env-type: 'dev'
            redis-image: 'redis:7.0-alpine'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry
      run: |
        curl -sSL \
          "https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py" | python

        # Adding `poetry` to `$PATH`:
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        poetry config virtualenvs.in-project true
        poetry run pip install -U pip
        poetry install --extras=${{ matrix.env-type }}

    - name: Pull and build docker-compose services
      run: |
        docker-compose pull
        docker-compose up --detach
      env:
        REDIS_IMAGE: ${{ matrix.redis-image }}

    - name: Run checks
      run: make test

    - name: Run doctests
      if: ${{ matrix.env-type == 'dev' }}
      run: |
        poetry run pytest \
          -p no:cov -o addopts="" \
          --doctest-modules --doctest-glob='*.md' \
          asyncio_redis_rate_limit README.md

    # Upload coverage to codecov: https://codecov.io/
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      if: ${{ matrix.python-version == '3.9' && matrix.env-type == 'dev' }}
      with:
        file: ./coverage.xml
